apiVersion: v1
kind: Service
metadata:
  name: dvdrentalpos-frontend
  labels:
    app: dvdrentalpos
spec:
  ports:
  - port: 8010
    targetPort: frontend
  selector:
    app: dvdrentalpos
    tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvdrentalpos-ingress
spec:
  rules:
  - host: dvdrentalpos.home.hpkns.uk
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: dvdrentalpos-frontend
            port:
              number: 8010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvdrentalpos-frontend
  labels:
    app: dvdrentalpos
spec:
  selector:
    matchLabels:
      app: dvdrentalpos
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dvdrentalpos
        tier: frontend
    spec:
      containers:
      - image: ghcr.io/lilopkins/dvdrentalpos-frontend:b9671e1cc8c71e3bfb8b050fd6c2d9cd0563dffd
        name: frontend
        ports:
        - containerPort: 80
          name: frontend
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
