apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvdrentalpos-backend
  labels:
    app: dvdrentalpos
spec:
  selector:
    matchLabels:
      app: dvdrentalpos
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dvdrentalpos
        tier: backend
    spec:
      containers:
      - image: ghcr.io/lilopkins/dvdrentalpos:b9671e1cc8c71e3bfb8b050fd6c2d9cd0563dffd
        name: backend
        ports:
        - containerPort: 8888
          name: backend
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
